### ISSUE TITLE
nilクラスの関数エラー

### ISSUE THREAD

**Issue by SatoshiTakiguchi** [SatoshiTakiguchi/debag_exam#1]
debag.rb:38:in `proc': undefined method `+' for nil:NilClass (NoMethodError)
            p path[0] + " => " + @data[path[0]].to_s\r
                      ^
        from debag.rb:49:in `<main>'

**Comment by SatoshiTakiguchi** [comment]
正しい出力は不明であるがエラーとなっている。この出力をしている箇所は38行目「p path[0] + " => " + @data[path[0]].to_s」である。
